import { students } from '@src/db/schemas'
import { seedId, type SeedTransaction } from './helpers'

/** Alunos fictícios, indexados por uma chave legível para os empréstimos */
export const STUDENTS = {
  anaBeatrizFerreira: {
    id: seedId('student', 1),
    registrationNumber: '2026001',
    email: 'ana.ferreira@aluno.archivum.test',
    name: 'Ana Beatriz Ferreira',
    educationLevel: 'FUNDAMENTAL',
    grade: 1,
    section: 'A',
    enrollmentYear: 2026,
    graduationYear: 2034,
    active: true,
  },
  brunoCarvalhoLima: {
    id: seedId('student', 2),
    registrationNumber: '2026002',
    email: 'bruno.lima@aluno.archivum.test',
    name: 'Bruno Carvalho Lima',
    educationLevel: 'FUNDAMENTAL',
    grade: 4,
    section: 'B',
    enrollmentYear: 2023,
    graduationYear: 2031,
    active: true,
  },
  camilaRodriguesSouza: {
    id: seedId('student', 3),
    registrationNumber: '2026003',
    email: 'camila.souza@aluno.archivum.test',
    name: 'Camila Rodrigues Souza',
    educationLevel: 'FUNDAMENTAL',
    grade: 6,
    section: 'C',
    enrollmentYear: 2021,
    graduationYear: 2029,
    active: true,
  },
  danielAlmeidaNunes: {
    id: seedId('student', 4),
    registrationNumber: '2026004',
    email: 'daniel.nunes@aluno.archivum.test',
    name: 'Daniel Almeida Nunes',
    educationLevel: 'FUNDAMENTAL',
    grade: 7,
    section: 'A',
    enrollmentYear: 2020,
    graduationYear: 2028,
    active: true,
  },
  eduardaMartinsRocha: {
    id: seedId('student', 5),
    registrationNumber: '2026005',
    email: 'eduarda.rocha@aluno.archivum.test',
    name: 'Eduarda Martins Rocha',
    educationLevel: 'FUNDAMENTAL',
    grade: 9,
    section: 'B',
    enrollmentYear: 2018,
    graduationYear: 2026,
    active: true,
  },
  felipeOliveiraBarbosa: {
    id: seedId('student', 6),
    registrationNumber: '2026006',
    email: 'felipe.barbosa@aluno.archivum.test',
    name: 'Felipe Oliveira Barbosa',
    educationLevel: 'FUNDAMENTAL',
    grade: 9,
    section: 'C',
    enrollmentYear: 2018,
    graduationYear: 2026,
    active: true,
  },
  gabrielaSantosPereira: {
    id: seedId('student', 7),
    registrationNumber: '2026007',
    email: 'gabriela.pereira@aluno.archivum.test',
    name: 'Gabriela Santos Pereira',
    educationLevel: 'MEDIO',
    grade: 1,
    section: 'A',
    enrollmentYear: 2026,
    graduationYear: 2028,
    active: true,
  },
  henriqueCostaRibeiro: {
    id: seedId('student', 8),
    registrationNumber: '2026008',
    email: 'henrique.ribeiro@aluno.archivum.test',
    name: 'Henrique Costa Ribeiro',
    educationLevel: 'MEDIO',
    grade: 1,
    section: 'B',
    enrollmentYear: 2026,
    graduationYear: 2028,
    active: true,
  },
  isabelaMoreiraCardoso: {
    id: seedId('student', 9),
    registrationNumber: '2026009',
    email: 'isabela.cardoso@aluno.archivum.test',
    name: 'Isabela Moreira Cardoso',
    educationLevel: 'MEDIO',
    grade: 2,
    section: 'A',
    enrollmentYear: 2025,
    graduationYear: 2027,
    active: true,
  },
  joaoPedroTavaresMendes: {
    id: seedId('student', 10),
    registrationNumber: '2026010',
    email: 'joao.mendes@aluno.archivum.test',
    name: 'João Pedro Tavares Mendes',
    educationLevel: 'MEDIO',
    grade: 3,
    section: 'A',
    enrollmentYear: 2024,
    graduationYear: 2026,
    active: true,
  },
} satisfies Record<string, typeof students.$inferInsert>

export async function seedStudents(tx: SeedTransaction): Promise<number> {
  const rows = Object.values(STUDENTS)

  await tx.insert(students).values(rows).onConflictDoNothing()

  return rows.length
}
